# Generated by Django 4.2.3 on 2023-08-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'COMBINACION DE COLORES'), ('D', 'DENOMINATIVA'), ('E', 'SECUENCIAL'), ('F', 'FIGURATIVA'), ('G', 'GUSTATIVA'), ('L', 'TACTIL'), ('M', 'MIXTA'), ('O', 'OLFATIVA'), ('P', 'POSICION'), ('R', 'TRIDIMENSIONAL MIXTA'), ('S', 'SONORA'), ('T', 'TRIDIMENSIONAL')], max_length=1)),
                ('denominacion', models.CharField(max_length=100)),
                ('fechapresentacion', models.DateField()),
                ('fechaotorgamiento', models.DateField()),
            ],
        ),
    ]
