# Generated by Django 4.2.3 on 2023-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorIP', '0002_mdindustriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='pmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('M', 'MODELO DE UTILIDAD'), ('P', 'PATENTE DE INVENCION')], max_length=1)),
                ('denominacion', models.CharField(max_length=100)),
                ('fechapresentacion', models.DateField()),
                ('fechaotorgamiento', models.DateField()),
            ],
        ),
    ]
