# Generated by Django 4.2.3 on 2023-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorIP', '0003_pmu'),
    ]

    operations = [
        migrations.CreateModel(
            name='obrasysoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('O', 'OBRAS LITERARIAS'), ('s', 'SOFTWARE')], max_length=1)),
                ('denominacion', models.CharField(max_length=100)),
                ('fechadeposito', models.DateField()),
                ('fechaconstancia', models.DateField()),
            ],
        ),
    ]
